<a href="https://colab.research.google.com/github/jyotidabass/Self-and-Cross-Attention-Mechanism/blob/main/Self_and_Cross_Attention_Mechanism.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
import numpy as np

def self_attention(query, keys, values, d_k):
    # Compute the attention scores
    attention_scores = np.dot(query, keys.T) / np.sqrt(d_k)

    # Normalize the attention scores using softmax
    # Subtract the maximum value for numerical stability
    exp_scores = np.exp(attention_scores - np.max(attention_scores, axis=0, keepdims=True))
    attention_weights = exp_scores / np.sum(exp_scores, axis=0, keepdims=True)

    # Compute the context vector by applying the attention weights to the values
    context_vector = np.dot(attention_weights, values)
    return context_vector

# Create example input tensors
query = np.array([[0.1, 0.2, 0.3]])  # Query vector (1 x dk)
keys = np.array([[0.1, 0.2, 0.3], [0.4, 0.5, 0.6], [0.7, 0.8, 0.9]])  # Key matrix (3 x dk)
values = np.array([[0.1, 0.2, 0.3], [0.4, 0.5, 0.6], [0.7, 0.8, 0.9]])  # Value matrix (3 x dk)
d_k = 3  # Dimension of keys

# Compute the context vector
context_vector = self_attention(query, keys, values, d_k)
print("Context vector shape:", context_vector.shape)
print("Context vector:", context_vector)

print("Query:", query)
print("Keys:", keys)
print("Values:", values)

print("Attention scores:", np.dot(query, keys.T))

Context vector shape: (1, 3)
Context vector: [[1.2 1.5 1.8]]
Query: [[0.1 0.2 0.3]]
Keys: [[0.1 0.2 0.3]
 [0.4 0.5 0.6]
 [0.7 0.8 0.9]]
Values: [[0.1 0.2 0.3]
 [0.4 0.5 0.6]
 [0.7 0.8 0.9]]
Attention scores: [[0.14 0.32 0.5 ]]


In [19]:
import numpy as np

def cross_attention(query, keys, values, d_k):
    # Compute the attention scores
    attention_scores = np.dot(query, keys.T) / np.sqrt(d_k)

    # Normalize the attention scores using softmax
    # Subtract the maximum value for numerical stability
    exp_scores = np.exp(attention_scores - np.max(attention_scores, axis=0, keepdims=True))
    attention_weights = exp_scores / np.sum(exp_scores, axis=0, keepdims=True)  # Manual softmax calculation

    # Compute the context vector by applying the attention weights to the values
    context_vector = np.dot(attention_weights, values)
    return context_vector

# Create example input tensors
query = np.array([[0.1, 0.2, 0.3]])  # Query vector (1 x dk)
keys = np.array([[0.1, 0.2, 0.3], [0.4, 0.5, 0.6], [0.7, 0.8, 0.9]])  # Key matrix (3 x dk)
values = np.array([[0.1, 0.2, 0.3], [0.4, 0.5, 0.6], [0.7, 0.8, 0.9]])  # Value matrix (3 x dk)
d_k = 3  # Dimension of keys

# Compute the context vector
context_vector = cross_attention(query, keys, values, d_k)
print("Context vector shape:", context_vector.shape)
print("Context vector:", context_vector)

print("Query:", query)
print("Keys:", keys)
print("Values:", values)


Context vector shape: (1, 3)
Context vector: [[1.2 1.5 1.8]]
Query: [[0.1 0.2 0.3]]
Keys: [[0.1 0.2 0.3]
 [0.4 0.5 0.6]
 [0.7 0.8 0.9]]
Values: [[0.1 0.2 0.3]
 [0.4 0.5 0.6]
 [0.7 0.8 0.9]]
